/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinica;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fabia
 */
public class Ficha extends javax.swing.JFrame {

    conexionsql cone = new conexionsql();
    classficha mane = new classficha();
    
    int fila;
    int codigo;
    
    int filaAdulto = 0;
    int codigoAdulto = 0;
    /**
     * Creates new form Ficha
     */
    public Ficha() {
        initComponents();
        this.setLocationRelativeTo(null);
        mane.cargartablaadulto(tablaPaciente);
        
        cargartabla();

        
        for (int i = 1; i <=100; i++){
            cbEdad.addItem(String.valueOf(i));
        }
        
        
        
        txtAnamnesis.setLineWrap(true);
        txtAnamnesis.setWrapStyleWord(true);
        
        
        txtObservaciones.setLineWrap(true);
        txtObservaciones.setWrapStyleWord(true);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupGenero = new javax.swing.ButtonGroup();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        groupHipertension = new javax.swing.ButtonGroup();
        groupTuberculosis = new javax.swing.ButtonGroup();
        groupHepatitis = new javax.swing.ButtonGroup();
        groupAlergias = new javax.swing.ButtonGroup();
        groupUlceras = new javax.swing.ButtonGroup();
        groupVih = new javax.swing.ButtonGroup();
        groupEpilepsia = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        rbMasculino = new javax.swing.JRadioButton();
        rbFemenino = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dcFechaNacimiento = new com.toedter.calendar.JDateChooser();
        txtLugarNacimiento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDomicilio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtOcupacion = new javax.swing.JTextField();
        cbEdad = new javax.swing.JComboBox<>();
        dcFecha = new com.toedter.calendar.JDateChooser();
        txtCelular = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAnamnesis = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtDiabetesTipo = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        rbHiperSi = new javax.swing.JRadioButton();
        rbHiperNo = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        rbTuberSi = new javax.swing.JRadioButton();
        rbTuberNo = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        rbHepaSi = new javax.swing.JRadioButton();
        rbHepaNo = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        rbAlergiasSi = new javax.swing.JRadioButton();
        rbAlergiasNo = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        rbUlceSi = new javax.swing.JRadioButton();
        rbUlceNo = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        rbVihSi = new javax.swing.JRadioButton();
        rbVihNo = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();
        rbEpiSi = new javax.swing.JRadioButton();
        rbEpiNo = new javax.swing.JRadioButton();
        jLabel27 = new javax.swing.JLabel();
        txtOtros = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtCual = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        btnAgregar = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel30 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtSeguimiento = new javax.swing.JTextArea();
        txtEstadoCivil = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaPaciente = new javax.swing.JTable();
        jLabel31 = new javax.swing.JLabel();
        txtBuscarPaciente = new javax.swing.JTextField();
        btnmenu = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Genero:");

        groupGenero.add(rbMasculino);
        rbMasculino.setText("M");

        groupGenero.add(rbFemenino);
        rbFemenino.setText("F");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("1. Datos Generales:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Nombre del paciente:");

        jLabel3.setText("Edad:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Fecha y lugar de nacimiento: ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Domicilio:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Estado Civil:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Ocupacion:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Fecha:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Cel.");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("2. Anamnesis:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Motivo de la consulta");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("¿Por qué vino a consulta? ¿Qué es lo que más le molesta? ¿Qué idea tiene usted de la enfermedad? ");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("¿Cuándo? (Fecha) ¿Cómo? (Forma de comienzo) ¿Por qué? (Causa desencadenante)");

        txtAnamnesis.setColumns(20);
        txtAnamnesis.setRows(5);
        jScrollPane2.setViewportView(txtAnamnesis);
        txtAnamnesis.getAccessibleContext().setAccessibleParent(jScrollPane1);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel15.setText("Ficha Clínica Odontológica");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("3. Anamnesis Médica:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("a) Personal");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("• Antecedentes mórbidos (marcar con una circulo) ");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("− Diabetes Tipo:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("− Hipertensión:");

        groupHipertension.add(rbHiperSi);
        rbHiperSi.setText("Si");

        groupHipertension.add(rbHiperNo);
        rbHiperNo.setText("No");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("− Tuberculosis:");

        groupTuberculosis.add(rbTuberSi);
        rbTuberSi.setText("Si");
        rbTuberSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTuberSiActionPerformed(evt);
            }
        });

        groupTuberculosis.add(rbTuberNo);
        rbTuberNo.setText("No");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("− Hepatitis A B C:");

        groupHepatitis.add(rbHepaSi);
        rbHepaSi.setText("Si");

        groupHepatitis.add(rbHepaNo);
        rbHepaNo.setText("No");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("− Alergias:");

        groupAlergias.add(rbAlergiasSi);
        rbAlergiasSi.setText("Si");

        groupAlergias.add(rbAlergiasNo);
        rbAlergiasNo.setText("No");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("− Úlceras o gastritis:");

        groupUlceras.add(rbUlceSi);
        rbUlceSi.setText("Si");

        groupUlceras.add(rbUlceNo);
        rbUlceNo.setText("No");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("− VIH:");

        groupVih.add(rbVihSi);
        rbVihSi.setText("Si");

        groupVih.add(rbVihNo);
        rbVihNo.setText("No");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Epilepsia ");

        groupEpilepsia.add(rbEpiSi);
        rbEpiSi.setText("Si");

        groupEpilepsia.add(rbEpiNo);
        rbEpiNo.setText("No");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Otros:");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("Cual:");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setText("Observación de Odontograma :");

        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(5);
        jScrollPane4.setViewportView(txtObservaciones);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Edad", "Fecha Nacimiento", "Lugar Nacimiento", "Domicilio", "Genero", "EstadoCivil", "Ocupacion", "Fecha", "Celular", "Anamnesis", "Diabetes", "Hipertension", "Tuberculosis", "Hepatitis", "Alergias", "Ulceras", "VIH", "Epilepsia", "Otros", "Cual", "Observaciones", "Seguimiento"
            }
        ));
        tabla.setAutoResizeMode(0);
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tabla);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setText("Seguimiento Del Paciente:");

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel35.setText("− Buscar:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtSeguimiento.setColumns(20);
        txtSeguimiento.setRows(5);
        jScrollPane7.setViewportView(txtSeguimiento);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        tablaPaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Identificacion", "Nombre", "Apellido", "Fecha Nacimiento", "Telefono", "Estado Civil", "Ocupacion", "Edad", "Sexo", "Direccion"
            }
        ));
        tablaPaciente.setAutoResizeMode(0);
        tablaPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPacienteMouseClicked(evt);
            }
        });
        tablaPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablaPacienteKeyPressed(evt);
            }
        });
        jScrollPane6.setViewportView(tablaPaciente);

        jLabel31.setText("Buscar: ");

        txtBuscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarPacienteActionPerformed(evt);
            }
        });
        txtBuscarPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarPacienteKeyPressed(evt);
            }
        });

        btnmenu.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar-sesion.png"))); // NOI18N
        btnmenu.setText("menu");
        btnmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel15)
                        .addGap(40, 40, 40)
                        .addComponent(btnmenu))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel29)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                                .addComponent(jLabel30)
                                .addComponent(jScrollPane7))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel17)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel19)
                                                    .addComponent(jLabel20)
                                                    .addComponent(jLabel21)
                                                    .addComponent(jLabel23)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel22)))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtDiabetesTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                                .addGap(8, 8, 8)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addComponent(rbTuberSi)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addComponent(rbTuberNo))
                                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addComponent(rbHiperSi)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addComponent(rbHiperNo))
                                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addComponent(rbHepaSi)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addComponent(rbHepaNo))))
                                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                    .addComponent(rbUlceSi)
                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                    .addComponent(rbUlceNo))
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                    .addComponent(rbAlergiasSi)
                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                    .addComponent(rbAlergiasNo))
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                    .addComponent(rbVihSi)
                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                    .addComponent(rbVihNo))))
                                                        .addGap(83, 83, 83)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel26)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(rbEpiSi)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(rbEpiNo))
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addComponent(jLabel28)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(txtCual))
                                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addComponent(jLabel27)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addComponent(txtOtros, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                                            .addComponent(jLabel25))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel12))
                                .addComponent(jLabel13)
                                .addComponent(jLabel14)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscar))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29)
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(rbMasculino)
                                    .addGap(18, 18, 18)
                                    .addComponent(rbFemenino)
                                    .addGap(33, 33, 33)
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(33, 33, 33)
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtOcupacion))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel2)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(dcFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtLugarNacimiento))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(28, 28, 28)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel15)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnmenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txtBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(cbEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(dcFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtLugarNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rbMasculino)
                    .addComponent(rbFemenino)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(txtOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)
                        .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtDiabetesTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel20))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbHiperSi)
                        .addComponent(rbHiperNo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbTuberNo)
                        .addComponent(jLabel26)
                        .addComponent(rbEpiSi)
                        .addComponent(rbEpiNo))
                    .addComponent(rbTuberSi)
                    .addComponent(jLabel21))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rbHepaSi)
                                .addComponent(rbHepaNo))
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(txtOtros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbAlergiasSi)
                        .addComponent(rbAlergiasNo)
                        .addComponent(jLabel28)
                        .addComponent(txtCual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbUlceSi)
                        .addComponent(rbUlceNo))
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbVihSi)
                        .addComponent(rbVihNo)))
                .addGap(38, 38, 38)
                .addComponent(jLabel29)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jLabel30)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(352, 352, 352))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1136, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        String sexoSeleccionado = "";
        if(rbMasculino.isSelected()){
            sexoSeleccionado = "Masculino";
        }
        if(rbFemenino.isSelected()){
            sexoSeleccionado = "Femenino";
        }

        String Hiper = "";
        if(rbHiperSi.isSelected()){
            Hiper = "Si";
        }
        if(rbHiperNo.isSelected()){
            Hiper = "No";
        }

        String Tuber = "";
        if(rbTuberSi.isSelected()){
            Tuber = "Si";
        }
        if(rbTuberNo.isSelected()){
            Tuber = "No";
        }

        String Hepa =  "";
        if(rbHepaSi.isSelected()){
            Hepa = "Si";
        }
        if(rbHepaNo.isSelected()){
            Hepa = "No";
        }

        String Aler = "";
        if(rbAlergiasSi.isSelected()){
            Aler = "Si";
        }
        if(rbAlergiasNo.isSelected()){
            Aler = "No";
        }

        String Ulce = "";
        if(rbUlceSi.isSelected()){
            Ulce = "Si";
        }
        if(rbUlceNo.isSelected()){
            Ulce = "No";
        }

        String vih = "";
        if(rbVihSi.isSelected()){
            vih = "Si";
        }
        if(rbVihNo.isSelected()){
            vih = "No";
        }

        String Epi = "";
        if(rbEpiSi.isSelected()){
            Epi = "Si";
        }
        if(rbEpiNo.isSelected()){
            Epi = "No";
        }

        String Nombre = txtNombre.getText();
        String Edad = cbEdad.getSelectedItem().toString();
        String FechaNacimiento = ( (JTextField) dcFechaNacimiento.getDateEditor().getUiComponent()).getText();
        String LugarNacimiento = txtLugarNacimiento.getText();
        String Domicilio = txtDomicilio.getText();
        String Genero = sexoSeleccionado;
        String EstadoCivil = txtEstadoCivil.getText();
        String Ocupacion = txtOcupacion.getText();
        String Fecha = ( (JTextField) dcFecha.getDateEditor().getUiComponent()).getText();
        String Celular = txtCelular.getText();
        String Anamnesis = txtAnamnesis.getText();
        String DiabetesTipo = txtDiabetesTipo.getText();
        String Hipertension = Hiper;
        String Tuberculosis = Tuber;
        String Hepatitis  = Hepa;
        String Alergias = Aler;
        String Ulceras = Ulce;
        String VIH = vih;
        String Epilepsia = Epi;
        String Otros = txtOtros.getText();
        String Cual = txtCual.getText();
        String Observaciones = txtObservaciones.getText();
        //String tipoCliente =  cbTipoCliente.getSelectedItem().toString();
        
        
        //String FechaSeguimiento = ( (JTextField) dcFechaSeguimiento.getDateEditor().getUiComponent()).getText();
        //String Descripcion = txtDescripcion.getText();
        String Seguimiento = txtSeguimiento.getText();
        //String OtrosSeguimiento = txtOtrosSeguimiento.getText();

        try {

            Connection con = cone.obtenerconexion();

            PreparedStatement sp = con.prepareStatement("INSERT INTO Historial_clinicoadulto(NombrePaciente, Edad, FechaNacimiento, LugarNacimiento, Domicilio, Genero, EstadoCivil, Ocupacion, Fecha, Celular, Anamnesis, DiabetesTipo, Hipertension, Tuberculosis, Hepatitis, Alergias, Ulceras, Vih, Epilepsia, Otros, Cual, Observaciones, Observacion_Seguimientopaciente)"
                + "Values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");

            //Los datos tambien pueden ser ingresados directamente en el query
            sp.setString(1, Nombre);
            sp.setString(2, Edad);
            sp.setString(3, FechaNacimiento);
            sp.setString(4, LugarNacimiento);
            sp.setString(5, Domicilio);
            sp.setString(6, Genero);
            sp.setString(7, EstadoCivil);
            sp.setString(8, Ocupacion);
            sp.setString(9, Fecha);
            sp.setString(10, Celular);
            sp.setString(11, Anamnesis);
            sp.setString(12, DiabetesTipo);
            sp.setString(13, Hipertension);
            sp.setString(14, Tuberculosis);
            sp.setString(15, Hepatitis);
            sp.setString(16, Alergias);
            sp.setString(17, Ulceras);
            sp.setString(18, VIH);
            sp.setString(19, Epilepsia);
            sp.setString(20, Otros);
            sp.setString(21, Cual);
            sp.setString(22, Observaciones);
            sp.setString(23, Seguimiento);
            //sp.setString(23, FechaSeguimiento);
            //sp.setString(24, Descripcion);
            //sp.setString(25, ObservaSeguimiento);
            //sp.setString(26, OtrosSeguimiento);

            //Para ejecutar el query
            sp.executeUpdate();

            JOptionPane.showMessageDialog(null, "Registro guardado correctamente");
            cargartabla();

            limpiar();

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(null, ex);

        }

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void rbTuberSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTuberSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbTuberSiActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
         DefaultTableModel modelotabla =  (DefaultTableModel) tabla.getModel();
        
        modelotabla.setRowCount(0);
        
        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        
        int columnas = 0;
                        //"insert into clientes (Identificacion, Nombre, Apellido, Sexo, Edad, TipoCliente)"+"Values(?,?,?,?,?,?)
        String sql = "SELECT CodigoFicha, NombrePaciente, Edad, FechaNacimiento, LugarNacimiento, Domicilio, Genero, EstadoCivil, Ocupacion, Fecha, Celular, Anamnesis, DiabetesTipo, Hipertension, Tuberculosis, Hepatitis, Alergias, Ulceras, Vih, Epilepsia, Otros, Cual, Observaciones, Observacion_Seguimientopaciente FROM Historial_clinicoadulto WHERE NombrePaciente LIKE '%" + txtBuscar.getText() + "%'";
                    //+"where Identificacion like '%"+txtbuscar.getText()+"%' or Nombre like '%"+txtbuscar.getText()+"%' or Apellido like '%"+txtbuscar.getText()+"%'"
                    //+"or Nombre like '%"+txtbuscar.getText()+"%'"
                    //+"or Apellido like '%"+txtbuscar.getText()+"%'";
        
        try
        {
            Connection con = cone.obtenerconexion();
            
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
        
            while(rs.next())
            {
               Object[] fila = new Object[columnas];
                for(int i = 0; i < columnas; i++)
                {
                 fila[i] = rs.getObject(i + 1);
                }
                
                modelotabla.addRow(fila); 
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.toString());
        }
       
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        
        
        
        
        
        
        
        try
        {
            String sexo1 = "";
            String Hiper1 = "";
            String Tuber1 = "";
            String Hepa1 = "";
            String Aler1 = "";
            String Ulce1 = "";
            String Vih1 = "";
            String Epi1 = "";
            fila = tabla.getSelectedRow();
            codigo = Integer.parseInt(tabla.getValueAt(fila, 0).toString());
            
            PreparedStatement ps;
            ResultSet rs;
            
            Connection con = cone.obtenerconexion();
            
            ps = con.prepareStatement("select * from Historial_clinicoadulto where CodigoFicha = ?");
            
            ps.setInt(1, codigo);
            rs = ps.executeQuery();
            
            while(rs.next())
            {
                txtNombre.setText(rs.getString("NombrePaciente"));
                cbEdad.setSelectedItem(rs.getString("Edad"));
                txtLugarNacimiento.setText(rs.getString("LugarNacimiento"));
                txtDomicilio.setText(rs.getString("Domicilio"));
                txtEstadoCivil.setText(rs.getString("EstadoCivil"));
                dcFechaNacimiento.setDate(rs.getDate("FechaNacimiento"));
                
                txtOcupacion.setText(rs.getString("Ocupacion"));
                dcFecha.setDate(rs.getDate("Fecha"));
                txtCelular.setText(rs.getString("Celular"));
                txtAnamnesis.setText(rs.getString("Anamnesis"));
                txtDiabetesTipo.setText(rs.getString("DiabetesTipo"));
                
                
                txtOtros.setText(rs.getString("Otros"));
                txtCual.setText(rs.getString("Cual"));
                txtObservaciones.setText(rs.getString("Observaciones"));
                txtSeguimiento.setText(rs.getString("Observacion_Seguimientopaciente"));
               
                
                //radio button
                
                
                sexo1 = rs.getString("Genero");
                if(sexo1.equals("Masculino"))
                {                   
                    rbMasculino.setSelected(true);                    
                }
                else
                {
                    rbFemenino.setSelected(true);                 
                }
                
                
                
                Hiper1 = rs.getString("Hipertension");
                if(Hiper1.equals("Si")){
                    rbHiperSi.setSelected(true);
                }else{
                    rbHiperNo.setSelected(true);
                }
                
                
                Tuber1 = rs.getString("Tuberculosis");
                if(Tuber1.equals("Si")){
                    rbTuberSi.setSelected(true);
                }else{
                    rbTuberNo.setSelected(true);
                }
                
                
                Hepa1 = rs.getString("Tuberculosis");
                if(Hepa1.equals("Si")){
                    rbHepaSi.setSelected(true);
                }else{
                    rbHepaNo.setSelected(true);
                }
                
                
                Aler1 = rs.getString("Alergias");
                if(Aler1.equals("Si")){
                    rbAlergiasSi.setSelected(true);
                }else{
                    rbAlergiasNo.setSelected(true);
                }
                
                
                Ulce1 = rs.getString("Ulceras");
                 if(Ulce1.equals("Si")){
                    rbUlceSi.setSelected(true);
                }else{
                    rbUlceNo.setSelected(true);
                }
                
                 
                Vih1 = rs.getString("Vih");
                 if(Vih1.equals("Si")){
                    rbVihSi.setSelected(true);
                }else{
                    rbVihNo.setSelected(true);
                }
                 
                 
                 
                Epi1 = rs.getString("Epilepsia");
                if(Epi1.equals("Si")){
                    rbEpiSi.setSelected(true);
                }else{
                    rbEpiNo.setSelected(true);
                }
            }
            
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.toString());
        }
        
        
        
        
        
 
        
        
    }//GEN-LAST:event_tablaMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
        
         try
        {
            Connection con = cone.obtenerconexion();
              
            PreparedStatement ps = con.prepareStatement("delete from Historial_clinicoadulto where CodigoFicha = ?");
            
            ps.setInt(1, codigo);
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Registro Eliminado");
            
            limpiar();
            cargartabla();
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e.toString());
        }
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    
    
    
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        
          String sexoSeleccionado = "";
        if(rbMasculino.isSelected()){
            sexoSeleccionado = "Masculino";
        }
        if(rbFemenino.isSelected()){
            sexoSeleccionado = "Femenino";
        }

        String Hiper = "";
        if(rbHiperSi.isSelected()){
            Hiper = "Si";
        }
        if(rbHiperNo.isSelected()){
            Hiper = "No";
        }

        String Tuber = "";
        if(rbTuberSi.isSelected()){
            Tuber = "Si";
        }
        if(rbTuberNo.isSelected()){
            Tuber = "No";
        }

        String Hepa =  "";
        if(rbHepaSi.isSelected()){
            Hepa = "Si";
        }
        if(rbHepaNo.isSelected()){
            Hepa = "No";
        }

        String Aler = "";
        if(rbAlergiasSi.isSelected()){
            Aler = "Si";
        }
        if(rbAlergiasNo.isSelected()){
            Aler = "No";
        }

        String Ulce = "";
        if(rbUlceSi.isSelected()){
            Ulce = "Si";
        }
        if(rbUlceNo.isSelected()){
            Ulce = "No";
        }

        String vih = "";
        if(rbVihSi.isSelected()){
            vih = "Si";
        }
        if(rbVihNo.isSelected()){
            vih = "No";
        }

        String Epi = "";
        if(rbEpiSi.isSelected()){
            Epi = "Si";
        }
        if(rbEpiNo.isSelected()){
            Epi = "No";
        }

        String Nombre = txtNombre.getText();
        String Edad = cbEdad.getSelectedItem().toString();
        String FechaNacimiento = ( (JTextField) dcFechaNacimiento.getDateEditor().getUiComponent()).getText();
        String LugarNacimiento = txtLugarNacimiento.getText();
        String Domicilio = txtDomicilio.getText();
        String Genero = sexoSeleccionado;
        String EstadoCivil = txtEstadoCivil.getText();
        String Ocupacion = txtOcupacion.getText();
        String Fecha = ( (JTextField) dcFecha.getDateEditor().getUiComponent()).getText();
        String Celular = txtCelular.getText();
        String Anamnesis = txtAnamnesis.getText();
        String DiabetesTipo = txtDiabetesTipo.getText();
        String Hipertension = Hiper;
        String Tuberculosis = Tuber;
        String Hepatitis  = Hepa;
        String Alergias = Aler;
        String Ulceras = Ulce;
        String VIH = vih;
        String Epilepsia = Epi;
        String Otros = txtOtros.getText();
        String Cual = txtCual.getText();
        String Observaciones = txtObservaciones.getText();
        //String tipoCliente =  cbTipoCliente.getSelectedItem().toString();
        
        
        //String FechaSeguimiento = ( (JTextField) dcFechaSeguimiento.getDateEditor().getUiComponent()).getText();
        //String Descripcion = txtDescripcion.getText();
        String Seguimiento = txtSeguimiento.getText();
        //String OtrosSeguimiento = txtOtrosSeguimiento.getText();

        try {

            Connection con = cone.obtenerconexion();

            PreparedStatement sp = con.prepareStatement("UPDATE Historial_clinicoadulto SET NombrePaciente = ?, Edad = ?, FechaNacimiento = ?, LugarNacimiento = ?, Domicilio = ?, Genero = ?, EstadoCivil = ?, Ocupacion = ?, Fecha = ?, Celular = ?, Anamnesis = ?, DiabetesTipo = ?, Hipertension = ?, Tuberculosis = ?, Hepatitis = ?, Alergias = ?, Ulceras = ?, Vih = ?, Epilepsia = ?, Otros = ?, Cual = ?, Observaciones = ?, Observacion_Seguimientopaciente = ? WHERE CodigoFicha = ?");

            //Los datos tambien pueden ser ingresados directamente en el query
            sp.setString(1, Nombre);
            sp.setString(2, Edad);
            sp.setString(3, FechaNacimiento);
            sp.setString(4, LugarNacimiento);
            sp.setString(5, Domicilio);
            sp.setString(6, Genero);
            sp.setString(7, EstadoCivil);
            sp.setString(8, Ocupacion);
            sp.setString(9, Fecha);
            sp.setString(10, Celular);
            sp.setString(11, Anamnesis);
            sp.setString(12, DiabetesTipo);
            sp.setString(13, Hipertension);
            sp.setString(14, Tuberculosis);
            sp.setString(15, Hepatitis);
            sp.setString(16, Alergias);
            sp.setString(17, Ulceras);
            sp.setString(18, VIH);
            sp.setString(19, Epilepsia);
            sp.setString(20, Otros);
            sp.setString(21, Cual);
            sp.setString(22, Observaciones);
            sp.setString(23, Seguimiento);
            sp.setInt(24, codigo);
            //sp.setString(23, FechaSeguimiento);
            //sp.setString(24, Descripcion);
            //sp.setString(25, ObservaSeguimiento);
            //sp.setString(26, OtrosSeguimiento);

            //Para ejecutar el query
            sp.executeUpdate();

            JOptionPane.showMessageDialog(null, "Registro guardado correctamente");
            cargartabla();

            limpiar();

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(null, ex);

        }
        
        
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void tablaPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPacienteMouseClicked
        
        String sexo2 = "";
        try{
            
            filaAdulto = tablaPaciente.getSelectedRow();
            codigoAdulto = Integer.parseInt(tablaPaciente.getValueAt(filaAdulto, 0).toString());
            
            PreparedStatement ps;
            ResultSet rs;
            
            Connection con = cone.obtenerconexion();
            
            CallableStatement cmd = con.prepareCall("{call mostraradultosesp(?)}");
            
            cmd.setInt(1, codigoAdulto);
            rs = cmd.executeQuery();
            
            
            while(rs.next()){
                txtNombre.setText(rs.getString("Nombre").replace(" ", "") + " " + rs.getString("Apellido"));
                //txtNombre.setText(rs.getString("NombreCompleto").replace(" ", ""));
                dcFechaNacimiento.setDate(rs.getDate("Fecha_Nacimiento"));
                txtCelular.setText(rs.getString("Telefono"));
                txtEstadoCivil.setText(rs.getString("Estado_Civil"));
                txtOcupacion.setText(rs.getString("Ocupacion"));
                cbEdad.setSelectedItem(Integer.toString(rs.getInt("Edad")));
                
                
                txtDomicilio.setText(rs.getString("Direccion"));
                
                sexo2 = rs.getString("Sexo").replace(" ", "");
                if(sexo2.equals("M")){
                    rbMasculino.setSelected(true);
                }else{
                    rbFemenino.setSelected(true);
                }
                
                
                
              
                
                
            }
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        
        
    }//GEN-LAST:event_tablaPacienteMouseClicked

    private void tablaPacienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaPacienteKeyPressed
       
        
        
        
        
        
        
    }//GEN-LAST:event_tablaPacienteKeyPressed

    private void txtBuscarPacienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarPacienteKeyPressed
      DefaultTableModel modelotabla =  (DefaultTableModel) tablaPaciente.getModel();
        
        modelotabla.setRowCount(0);
        
        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        
        int columnas = 0;
                        //"insert into clientes (Identificacion, Nombre, Apellido, Sexo, Edad, TipoCliente)"+"Values(?,?,?,?,?,?)
        String sql = "select Cod_paciente,Id_paciente, Nombre,Apellido, Fecha_Nacimiento, Telefono, Estado_Civil, Ocupacion, Edad, Sexo, Direccion from Paciente where Id_paciente like '%"+txtBuscarPaciente.getText()+"%' or Nombre like '%"+txtBuscarPaciente.getText()+"%' or Apellido like '%"+txtBuscarPaciente.getText()+"%'";
                    //+"where Identificacion like '%"+txtbuscar.getText()+"%' or Nombre like '%"+txtbuscar.getText()+"%' or Apellido like '%"+txtbuscar.getText()+"%'";
                    //+"or Nombre like '%"+txtbuscar.getText()+"%'"
   
        
        try
        {
            Connection con = cone.obtenerconexion();
            
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
        
            while(rs.next())
            {
               Object[] fila = new Object[columnas];
                for(int i = 0; i < columnas; i++)
                {
                 fila[i] = rs.getObject(i + 1);
                }
                
                modelotabla.addRow(fila); 
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.toString());
        }
        
    }//GEN-LAST:event_txtBuscarPacienteKeyPressed

    private void txtBuscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarPacienteActionPerformed

    private void btnmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuActionPerformed
        // TODO add your handling code here:
        menu nuevoFormulario = new menu();
        nuevoFormulario.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnmenuActionPerformed

    
    
    
    
    private void cargartabla()
    {
        DefaultTableModel modelotabla =  (DefaultTableModel) tabla.getModel();
        
        modelotabla.setRowCount(0);
        
        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        
        int columnas;
        
        try
        {
            Connection con = cone.obtenerconexion();
            ps = con.prepareStatement("select CodigoFicha,NombrePaciente,Edad,FechaNacimiento,LugarNacimiento,Domicilio,Genero,EstadoCivil,Ocupacion,Fecha,Celular,Anamnesis,DiabetesTipo,Hipertension,Tuberculosis,Hepatitis,Alergias,Ulceras,Vih,Epilepsia,Otros,Cual,Observaciones,Observacion_Seguimientopaciente from Historial_clinicoadulto");
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            
            while(rs.next())
            {
               Object[] fila = new Object[columnas];
                for(int i = 0; i < columnas; i++)
                {
                 fila[i] = rs.getObject(i + 1);
                }
                
                modelotabla.addRow(fila); 
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }
    
    
    
    public void limpiar(){
        txtNombre.setText("");
        cbEdad.setSelectedIndex(0);
        txtLugarNacimiento.setText("");
        txtDomicilio.setText("");
        txtEstadoCivil.setText("");
        dcFechaNacimiento.setDate(null);
                
        txtOcupacion.setText("");
        dcFecha.setDate(null);
        txtCelular.setText("");
        txtAnamnesis.setText("");
        txtDiabetesTipo.setText("");
                
                
        txtOtros.setText("");
        txtCual.setText("");
        txtObservaciones.setText("");
        txtSeguimiento.setText("");
        
        
        groupGenero.clearSelection();
        groupHipertension.clearSelection();
        groupTuberculosis.clearSelection();
        groupHepatitis.clearSelection();
        groupAlergias.clearSelection();
        groupUlceras.clearSelection();
        groupVih.clearSelection();
        groupEpilepsia.clearSelection();
        
        
        
    }
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ficha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ficha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ficha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ficha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ficha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnmenu;
    private javax.swing.JComboBox<String> cbEdad;
    private com.toedter.calendar.JDateChooser dcFecha;
    private com.toedter.calendar.JDateChooser dcFechaNacimiento;
    private javax.swing.ButtonGroup groupAlergias;
    private javax.swing.ButtonGroup groupEpilepsia;
    private javax.swing.ButtonGroup groupGenero;
    private javax.swing.ButtonGroup groupHepatitis;
    private javax.swing.ButtonGroup groupHipertension;
    private javax.swing.ButtonGroup groupTuberculosis;
    private javax.swing.ButtonGroup groupUlceras;
    private javax.swing.ButtonGroup groupVih;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JRadioButton rbAlergiasNo;
    private javax.swing.JRadioButton rbAlergiasSi;
    private javax.swing.JRadioButton rbEpiNo;
    private javax.swing.JRadioButton rbEpiSi;
    private javax.swing.JRadioButton rbFemenino;
    private javax.swing.JRadioButton rbHepaNo;
    private javax.swing.JRadioButton rbHepaSi;
    private javax.swing.JRadioButton rbHiperNo;
    private javax.swing.JRadioButton rbHiperSi;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JRadioButton rbTuberNo;
    private javax.swing.JRadioButton rbTuberSi;
    private javax.swing.JRadioButton rbUlceNo;
    private javax.swing.JRadioButton rbUlceSi;
    private javax.swing.JRadioButton rbVihNo;
    private javax.swing.JRadioButton rbVihSi;
    private javax.swing.JTable tabla;
    private javax.swing.JTable tablaPaciente;
    private javax.swing.JTextArea txtAnamnesis;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtBuscarPaciente;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCual;
    private javax.swing.JTextField txtDiabetesTipo;
    private javax.swing.JTextField txtDomicilio;
    private javax.swing.JTextField txtEstadoCivil;
    private javax.swing.JTextField txtLugarNacimiento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextArea txtObservaciones;
    private javax.swing.JTextField txtOcupacion;
    private javax.swing.JTextField txtOtros;
    private javax.swing.JTextArea txtSeguimiento;
    // End of variables declaration//GEN-END:variables
}
