/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinica;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import javax.swing.JButton;

/**
 *
 * @author crist
 */
public class menu extends javax.swing.JFrame {
    public JButton getBtnUsuario() {
        return btnusuario; // Suponiendo que el botón se llama btnUsuario
    }

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton8 = new javax.swing.JButton();
        btnexpediente = new javax.swing.JButton();
        btnconsentimiento = new javax.swing.JButton();
        btncalendarizacion = new javax.swing.JButton();
        btnpaciente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        btnusuario = new javax.swing.JButton();
        btnincapcidad = new javax.swing.JButton();
        btnconsentimiento1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jButton8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/public-service.png"))); // NOI18N
        jButton8.setText("Usuarios");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnexpediente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnexpediente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/expediente.png"))); // NOI18N
        btnexpediente.setText("Expediente");
        btnexpediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexpedienteActionPerformed(evt);
            }
        });

        btnconsentimiento.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnconsentimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consentimiento.png"))); // NOI18N
        btnconsentimiento.setText("Consentimiento");
        btnconsentimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsentimientoActionPerformed(evt);
            }
        });

        btncalendarizacion.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btncalendarizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calendario (1).png"))); // NOI18N
        btncalendarizacion.setText("Citas");
        btncalendarizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalendarizacionActionPerformed(evt);
            }
        });

        btnpaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnpaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cliente.png"))); // NOI18N
        btnpaciente.setText("Paciente");
        btnpaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpacienteActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu (1).png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setText("Bienvenido Menu principal");

        jButton6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/izquierda.png"))); // NOI18N
        jButton6.setText("Regresar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        btnusuario.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dentista.png"))); // NOI18N
        btnusuario.setText("Usuarios");
        btnusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnusuarioActionPerformed(evt);
            }
        });

        btnincapcidad.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnincapcidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/validacion.png"))); // NOI18N
        btnincapcidad.setText("Incapacidad");
        btnincapcidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnincapcidadActionPerformed(evt);
            }
        });

        btnconsentimiento1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnconsentimiento1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consentimiento.png"))); // NOI18N
        btnconsentimiento1.setText("Odontopediatria");
        btnconsentimiento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsentimiento1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carpeta.png"))); // NOI18N
        jButton1.setText("Seguros");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)))
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnpaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btncalendarizacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnconsentimiento1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnexpediente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnincapcidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnconsentimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(123, 123, 123))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnpaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnexpediente, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnincapcidad, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncalendarizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnconsentimiento1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnconsentimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
 
         Login nuevoFormulario = new Login();
        nuevoFormulario.setVisible(true);
        
        this.dispose();
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnpacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpacienteActionPerformed
    
          paciente nuevoFormulario = new paciente();
        nuevoFormulario.setVisible(true);
        
        this.dispose();
        
        
        
        
        
        
    }//GEN-LAST:event_btnpacienteActionPerformed

    private void btnexpedienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexpedienteActionPerformed
      
        expediente nuevoFormulario = new expediente();
        nuevoFormulario.setVisible(true);
        
        this.dispose();
        
        
        
    }//GEN-LAST:event_btnexpedienteActionPerformed

    private void btnusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnusuarioActionPerformed
      
         usuarios nuevoFormulario = new usuarios();
        nuevoFormulario.setVisible(true);
        
        this.dispose();
        
        
        
        
    }//GEN-LAST:event_btnusuarioActionPerformed

    private void btnincapcidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnincapcidadActionPerformed
        
        
          incapacidad nuevoFormulario = new incapacidad();
        nuevoFormulario.setVisible(true);
        
        this.dispose();
        
        
        
    }//GEN-LAST:event_btnincapcidadActionPerformed

    private void btnconsentimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsentimientoActionPerformed
       
            Consentimiento nuevoFormulario = new Consentimiento();
        nuevoFormulario.setVisible(true);
        
        this.dispose();
        
        
        
        
    }//GEN-LAST:event_btnconsentimientoActionPerformed

    private void btncalendarizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalendarizacionActionPerformed
    
           calendarizacion nuevoFormulario = new calendarizacion();
        nuevoFormulario.setVisible(true);
        
        this.dispose();
        
        
        
    }//GEN-LAST:event_btncalendarizacionActionPerformed

    private void btnconsentimiento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsentimiento1ActionPerformed
        // TODO add your handling code here:
        odontopediatria nuevoFormulario = new odontopediatria();
        nuevoFormulario.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnconsentimiento1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String rutaCarpetaSeguros = System.getProperty("user.home") + "/Desktop/seguros";

    // Creamos un objeto File con la ruta de la carpeta
    File carpetaSeguros = new File(rutaCarpetaSeguros);

    try {
        // Verificamos si Desktop es compatible con la plataforma actual
        if (Desktop.isDesktopSupported() && carpetaSeguros.exists()) {
            // Abre la carpeta y con el estilo del sistema
            Desktop.getDesktop().open(carpetaSeguros);
        } else {
            // Si la carpeta no existe mostrar ese mensaje
            javax.swing.JOptionPane.showMessageDialog(this, "Verifique que la carpeta 'seguros' existe en el escritorio.");
        }
    } catch (IOException e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncalendarizacion;
    private javax.swing.JButton btnconsentimiento;
    private javax.swing.JButton btnconsentimiento1;
    private javax.swing.JButton btnexpediente;
    private javax.swing.JButton btnincapcidad;
    private javax.swing.JButton btnpaciente;
    private javax.swing.JButton btnusuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
