/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinica;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import java.sql.*;

/**
 *
 * @author crist
 */


public class paciente extends javax.swing.JFrame {
    
    int fila, codigo;
    String identidad1 ="";
    classpaciente paci = new classpaciente();
    mantenimiento man = new mantenimiento();
    String ruta1 = "";
    conexionsql cone = new conexionsql();  
    boolean seleccion = false;

    /**
     * Creates new form paciente
     */
    public paciente() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        for (int i = 30; i < 250; i++) {
            String var = String.valueOf(i);
            cbpeso.addItem(String.valueOf(var));
        }
        
         for (int i = 2; i < 99; i++) {
            String var = String.valueOf(i);
            cbedad.addItem(String.valueOf(var));
        }
        
         cbEtapaVida.addItem("Niño");
         cbEtapaVida.addItem("Adulto");
         

         
         cbestadocivil.addItem("Soltero");
         cbestadocivil.addItem("Casado");
         cbestadocivil.addItem("Divorciado");
         
         cbtipopaciente.addItem("Paciente común");
         cbtipopaciente.addItem("Paciente integral");

         
         btneliminar.enable(false);
         btnmodificar.enable(false);
         
         cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RadioButtonSexo = new javax.swing.ButtonGroup();
        btnmenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtocupacion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        detallespaciente = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnbuscar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        btnagregar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        btneliminar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        DateChooser = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtbuscar = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        txtidentidad = new javax.swing.JTextField();
        cbtipopaciente = new javax.swing.JComboBox<>();
        cbedad = new javax.swing.JComboBox<>();
        txttelefono = new javax.swing.JTextField();
        rbmasculino = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        rbfemenino = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbpeso = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtnacionalidad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbestadocivil = new javax.swing.JComboBox<>();
        btnmodificar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnbuscarcarpeta = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnabrircarpeta = new javax.swing.JButton();
        txtruta = new javax.swing.JTextField();
        txtTalla = new javax.swing.JTextField();
        cbEtapaVida = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        btnlimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnmenu.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar-sesion.png"))); // NOI18N
        btnmenu.setText("Menu");
        btnmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/paciente.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setText("Formulario paciente");

        txtocupacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtocupacionKeyTyped(evt);
            }
        });

        detallespaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No. Identidad", "Nombre", "Apellido", "Teléfono", "Edad", "Etapa_vida", "Sexo", "Correo", "Peso (LB)", "Talla (CM)", "Tipo paciente", "Fecha nacimiento", "Estado civil", "Nacionalidad", "Ocupación", "Dirección"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        detallespaciente.setAutoResizeMode(0);
        detallespaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detallespacienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(detallespaciente);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Dirección");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("Fecha de nacimiento");

        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/busqueda.png"))); // NOI18N
        btnbuscar.setText("Buscar ");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Peso (Lb)");

        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-agregar.png"))); // NOI18N
        btnagregar.setText("Agregar");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setText("Talla (cm)");

        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel15.setText("Nacionalidad");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel16.setText("Estado civil");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel18.setText("Detalles");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel17.setText("Ocupacion");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel19.setText("No identidad");

        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });

        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbuscarKeyTyped(evt);
            }
        });

        txtapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapellidoKeyTyped(evt);
            }
        });

        txtidentidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidentidadKeyTyped(evt);
            }
        });

        txttelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelefonoKeyTyped(evt);
            }
        });

        RadioButtonSexo.add(rbmasculino);
        rbmasculino.setText("M");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Nombre");

        RadioButtonSexo.add(rbfemenino);
        rbfemenino.setText("F");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Apellido");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Número de Identidad");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Tipo de paciente");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Edad");

        txtnacionalidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnacionalidadKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Número telefónico");

        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-editar.png"))); // NOI18N
        btnmodificar.setText("modificar");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Sexo");

        btnbuscarcarpeta.setText("Buscar Carpeta");
        btnbuscarcarpeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarcarpetaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Correo electrónico");

        btnabrircarpeta.setText("Abrir Carpeta");
        btnabrircarpeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnabrircarpetaActionPerformed(evt);
            }
        });

        txtTalla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTallaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTallaKeyTyped(evt);
            }
        });

        cbEtapaVida.setMaximumRowCount(2);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel20.setText("Etapa de vida");

        btnlimpiar.setText("Limpiar");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtruta, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnbuscarcarpeta)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel6))
                                            .addComponent(jLabel14)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(284, 284, 284)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(cbedad, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(rbmasculino)
                                                            .addGap(30, 30, 30)
                                                            .addComponent(rbfemenino)
                                                            .addGap(35, 35, 35)))
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel7)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(cbtipopaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(DateChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jLabel12)
                                                    .addComponent(txtTalla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(220, 220, 220)
                                                        .addComponent(jLabel9))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(149, 149, 149)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel13)
                                                            .addComponent(cbpeso, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel17)
                                            .addComponent(txtidentidad, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbestadocivil, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtocupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel20)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(cbEtapaVida, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(52, 52, 52)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel8)
                                                .addComponent(txtnacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel15)
                                                .addComponent(jLabel11)
                                                .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel10)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(btnmenu)
                                                    .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnmodificar)
                                            .addComponent(btnlimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(btnabrircarpeta)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(183, 183, 183)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnbuscar)
                                .addGap(52, 52, 52)
                                .addComponent(btnagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbtipopaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtidentidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbEtapaVida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbestadocivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtocupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 21, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rbfemenino)
                                .addComponent(rbmasculino))
                            .addComponent(DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbpeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnlimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscarcarpeta)
                    .addComponent(btnabrircarpeta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(btnbuscar)
                            .addComponent(btnagregar)
                            .addComponent(btneliminar)
                            .addComponent(btnmodificar))
                        .addGap(31, 31, 31)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuActionPerformed
       
        
             menu nuevoFormulario = new menu();
        nuevoFormulario.setVisible(true);
        
        this.dispose();
        
        
        
    }//GEN-LAST:event_btnmenuActionPerformed

    private void txtocupacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtocupacionKeyTyped
        // TODO add your handling code here:
        man.sololetras(txtocupacion, evt);
    }//GEN-LAST:event_txtocupacionKeyTyped

    private void detallespacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detallespacienteMouseClicked

        btneliminar.enable(true);
        btnmodificar.enable(true);

        seleccion = true;

        String sexo1 = "";
        try {

            fila = detallespaciente.getSelectedRow();
            identidad1 = detallespaciente.getValueAt(fila, 0).toString();

            ResultSet rs;

            Connection con = cone.obtenerconexion();

            CallableStatement cmd = con.prepareCall("{CALL mostrarpaciente(?)}");

            cmd.setString(1, identidad1);

            rs = cmd.executeQuery();

            while (rs.next()) {

                codigo = (rs.getInt("Cod_paciente"));
                txtidentidad.setText(rs.getString("Id_paciente"));
                txtnombre.setText(rs.getString("Nombre").replace(" ", ""));
                txtapellido.setText(rs.getString("Apellido").replace(" ", ""));
                txttelefono.setText(rs.getString("Telefono"));
                cbedad.setSelectedItem(rs.getString("Edad"));
                cbEtapaVida.setSelectedItem(rs.getString("Etapa_vida").replace(" ", ""));
                sexo1 = rs.getString("Sexo").replace(" ", "");
                txtcorreo.setText(rs.getString("Correo"));
                cbpeso.setSelectedItem(rs.getString("Peso"));
                txtTalla.setText(rs.getString("Talla"));
                cbtipopaciente.setSelectedItem(rs.getString("Tipo_paciente"));
                String fecha = rs.getString("Fecha_Nacimiento");
                DateChooser.setDate((Date.valueOf(fecha)));
                cbestadocivil.setSelectedItem(rs.getString("Estado_Civil").replace(" ", ""));
                txtnacionalidad.setText(rs.getString("Nacionalidad"));
                txtocupacion.setText(rs.getString("Ocupacion"));
                txtdireccion.setText(rs.getString("Direccion"));

                if (sexo1.equals("F")) {
                    rbfemenino.setSelected(true);
                } else {
                    rbmasculino.setSelected(true);
                }

            }

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_detallespacienteMouseClicked

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed

        // JOptionPane.showMessageDialog(null, "LLenado "+ llenadoDNI());
        
            if (llenadoDNI()) {

            String sexo1 = "";
            try {

            fila = detallespaciente.getSelectedRow();
            //identidad1 = detallespaciente.getValueAt(fila, 0).toString();

            ResultSet rs;

            Connection con = cone.obtenerconexion();

                CallableStatement cmd = con.prepareCall("{CALL mostrarpaciente(?)}");

                        String DNI = txtbuscar.getText();

                        cmd.setString(1, DNI);

                        rs = cmd.executeQuery();

                    while (rs.next()) {

                    codigo = (rs.getInt("Cod_paciente"));
                    txtidentidad.setText(rs.getString("Id_paciente"));
                    txtnombre.setText(rs.getString("Nombre").replace(" ", ""));
                    txtapellido.setText(rs.getString("Apellido").replace(" ", ""));
                    txttelefono.setText(rs.getString("Telefono"));
                    cbedad.setSelectedItem(rs.getString("Edad"));
                    cbEtapaVida.setSelectedItem(rs.getString("Etapa_vida").replace(" ", ""));
                    sexo1 = rs.getString("Sexo").replace(" ", "");
                    txtcorreo.setText(rs.getString("Correo"));
                    cbpeso.setSelectedItem(rs.getString("Peso"));
                    txtTalla.setText(rs.getString("Talla"));
                    cbtipopaciente.setSelectedItem(rs.getString("Tipo_paciente"));
                    String fecha = rs.getString("Fecha_Nacimiento");
                    DateChooser.setDate((Date.valueOf(fecha)));
                    cbestadocivil.setSelectedItem(rs.getString("Estado_Civil").replace(" ", ""));
                    txtnacionalidad.setText(rs.getString("Nacionalidad"));
                    txtocupacion.setText(rs.getString("Ocupacion"));
                    txtdireccion.setText(rs.getString("Direccion"));

                    if (sexo1.equals("F")) {
                        rbfemenino.setSelected(true);
                    } else {
                        rbmasculino.setSelected(true);
                    }

                }

            } catch (SQLException e) {

                JOptionPane.showMessageDialog(null, e);
            }
             
            
            }else{
                
                JOptionPane.showMessageDialog(null, "Por favor debe rellenar el campo identidad.");
        }
    }//GEN-LAST:event_btnbuscarActionPerformed

    public boolean llenadoDNI(){
        
        if(txtidentidad.getText().equals("")) {
            return true;
        }else{
            return false;
        }
    }

    
    
    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed

        
        if (camposLlenos()) {
            
            String sexo = "";
            try {
                String nombrePaciente = txtnombre.getText().trim() + " " + txtapellido.getText().trim() + " " + txtidentidad.getText().trim();
            String rutaCarpetaPaciente = System.getProperty("user.home") + File.separator + "Desktop" + File.separator + "paciente";
            String rutaNuevaCarpeta = rutaCarpetaPaciente + File.separator + nombrePaciente;
            
            // Crear la carpeta "paciente" en el escritorio si no existe
            File carpetaPaciente = new File(rutaCarpetaPaciente);
            if (!carpetaPaciente.exists()) {
                carpetaPaciente.mkdir();
            }

            // Verificar si ya existe una carpeta con el mismo nombre del paciente
            File nuevaCarpeta = new File(rutaNuevaCarpeta);
            if (nuevaCarpeta.exists()) {
                JOptionPane.showMessageDialog(null, "Ya existe una carpeta con el nombre del paciente.");
            } else {
                nuevaCarpeta.mkdir();
                JOptionPane.showMessageDialog(null, "Carpeta creada con éxito para el paciente: " + nombrePaciente);
            }

                if (rbmasculino.isSelected()) {
                    sexo = "M";
                }else
                {
                    sexo = "F";
                }

                String fechaNA = ( (JTextField) DateChooser.getDateEditor().getUiComponent()).getText();
                int edad = edad = Integer.parseInt(cbedad.getSelectedItem().toString());
                String tipopaciente = cbtipopaciente.getSelectedItem().toString();
                String estadocivil = cbestadocivil.getSelectedItem().toString();
                Float talla = Float.parseFloat(txtTalla.getText().toString());
                Float peso = Float.parseFloat(cbpeso.getSelectedItem().toString());
                String etapavida = cbEtapaVida.getSelectedItem().toString();

                paci.AgregarPaciente(0, txtidentidad.getText(), txtnombre.getText(), txtapellido.getText(), txttelefono.getText(),
                    edad, etapavida, sexo, txtcorreo.getText(), peso, talla, tipopaciente,
                    fechaNA, estadocivil, txtnacionalidad.getText(), txtocupacion.getText(), txtdireccion.getText(), "agregar");

                JOptionPane.showMessageDialog(null, "Paciente " + txtnombre.getText() + " ha sido registrado con éxito.");
                cargarTabla();
                limpiar();
            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, e);

            }
            

        }else{

            JOptionPane.showMessageDialog(null, "Por favor llene todos los campos del paciente.");

        }
        
        
        //AGREGAR CAPRETA AUTOMATICAMENTE
        
        

    }//GEN-LAST:event_btnagregarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed

        if (seleccion == true) {

            int respuesta = JOptionPane.showConfirmDialog(null, "¿Deseas eliminar el registro seleccionado?", "Confirmación", JOptionPane.YES_NO_OPTION);

            if (respuesta == JOptionPane.YES_OPTION) {
                String fechaNA = ( (JTextField) DateChooser.getDateEditor().getUiComponent()).getText();
                paci.AgregarPaciente(codigo, "a", "a", "a", "1", 0, "a", "a", "a", 2.f, 2.f, "a", fechaNA, "a", "a", "a", "a", "eliminar");
                JOptionPane.showMessageDialog(null, "Registro eliminado con éxito.");
                cargarTabla();
                limpiar();
                seleccion = false;
            } else {
                JOptionPane.showMessageDialog(null,"Operación cancelada por el usuario.");
                limpiar();
            }

        }else{

            JOptionPane.showMessageDialog(null, "Por favor seleccione de la tabla un registro que desea eliminar.");

        }

    }//GEN-LAST:event_btneliminarActionPerformed

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
        // TODO add your handling code here:
        man.sololetras(txtnombre,evt);
    }//GEN-LAST:event_txtnombreKeyTyped

    private void txtbuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyTyped
        // TODO add your handling code here:
        man.solonumeros(txtbuscar, evt);
    }//GEN-LAST:event_txtbuscarKeyTyped

    private void txtapellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidoKeyTyped
        // TODO add your handling code here:
        man.sololetras(txtapellido, evt);
    }//GEN-LAST:event_txtapellidoKeyTyped

    private void txtidentidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidentidadKeyTyped
        // TODO add your handling code here:
        man.solonumeros(txtidentidad, evt);
    }//GEN-LAST:event_txtidentidadKeyTyped

    private void txttelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonoKeyTyped
        // TODO add your handling code here:
        man.solonumeros(txttelefono, evt);
    }//GEN-LAST:event_txttelefonoKeyTyped

    private void txtnacionalidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnacionalidadKeyTyped
        // TODO add your handling code here:
        man.sololetras (txtnacionalidad, evt);
    }//GEN-LAST:event_txtnacionalidadKeyTyped

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed

        if (seleccion == true) {

            if(camposLlenos()){

                String sexo = "";
                try {

                    if (rbmasculino.isSelected()) {
                        sexo = "M";
                    }else
                    {
                        sexo = "F";
                    }

                    String fechaNA = ( (JTextField) DateChooser.getDateEditor().getUiComponent()).getText();
                    int edad = Integer.parseInt(cbedad.getSelectedItem().toString());
                    String tipopaciente = cbtipopaciente.getSelectedItem().toString();
                    String estadocivil = cbestadocivil.getSelectedItem().toString();
                    Float talla = Float.parseFloat(txtTalla.getText().toString());
                    Float peso = Float.parseFloat(cbpeso.getSelectedItem().toString());
                    String etapavida = cbEtapaVida.getSelectedItem().toString();

                    paci.AgregarPaciente(codigo, txtidentidad.getText(), txtnombre.getText(), txtapellido.getText(), txttelefono.getText(),
                        edad, etapavida, sexo, txtcorreo.getText(), peso, talla, tipopaciente,
                        fechaNA, estadocivil, txtnacionalidad.getText(), txtocupacion.getText(), txtdireccion.getText(), "actualizar");
                    JOptionPane.showMessageDialog(null, "Paciente " + txtnombre.getText() + " ha sido actualizado con éxito.");
                    cargarTabla();
                    limpiar();

                } catch (Exception e) {

                    JOptionPane.showMessageDialog(null, e);

                }

                seleccion = false;

            }else{

                JOptionPane.showMessageDialog(null, "Por favor llene todos los campos del paciente.");

            }

        }else{

            JOptionPane.showMessageDialog(null, "Por favor seleccione de la tabla un registro que desea modificar.");

        }

    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btnbuscarcarpetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarcarpetaActionPerformed

        JFileChooser archivo = new JFileChooser();
        archivo.setCurrentDirectory(new File(System.getProperty("user.home") + "/Desktop/paciente"));
        archivo.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int option = archivo.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
        File selectedFolder = archivo.getSelectedFile();
        String folderPath = selectedFolder.getAbsolutePath();
        txtruta.setText(folderPath);
        ruta1 = folderPath;
    }
    }//GEN-LAST:event_btnbuscarcarpetaActionPerformed

    private void btnabrircarpetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnabrircarpetaActionPerformed
        String anexo = "C:\\Windows\\System32\\cmd.exe /K start ";
        
        try {
        Desktop.getDesktop().open(new File(ruta1));
    } catch (IOException ex) {
        Logger.getLogger(paciente.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnabrircarpetaActionPerformed

    private void txtTallaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTallaKeyPressed
     
    }//GEN-LAST:event_txtTallaKeyPressed

    private void txtTallaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTallaKeyTyped
        // TODO add your handling code here:
        man.solonumeros(txttelefono, evt);
    }//GEN-LAST:event_txtTallaKeyTyped

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnlimpiarActionPerformed

    public void limpiar(){
        
        
        cbEtapaVida.setSelectedIndex(0);
        txtnombre.setText("");
        txtapellido.setText("");
        txtidentidad.setText("");
        txttelefono.setText("");
        cbtipopaciente.setSelectedIndex(0);
        cbedad.setSelectedIndex(0);
        txtcorreo.setText("");
        txtdireccion.setText("");
        DateChooser.setDate(null);
        RadioButtonSexo.clearSelection();     
        cbestadocivil.setSelectedIndex(0);
        txtnacionalidad.setText("");
        txtocupacion.setText("");
        txtTalla.setText("");
        cbpeso.setSelectedIndex(0);
        
    }
    
    private boolean camposLlenos() {
    if (!rbfemenino.isSelected() && !rbmasculino.isSelected()) {
        return false;
    }
    if (cbEtapaVida.getSelectedIndex() == -1) {
        return false;
    }
    if (txtnombre.getText().isEmpty() || txtapellido.getText().isEmpty() || txtidentidad.getText().isEmpty() ||
        txttelefono.getText().isEmpty() || cbtipopaciente.getSelectedIndex() == -1 || cbedad.getSelectedIndex() == -1 ||
        txtcorreo.getText().isEmpty() || txtdireccion.getText().isEmpty() || DateChooser.getDate() == null ||
        cbestadocivil.getSelectedIndex() == -1 || txtnacionalidad.getText().isEmpty() || txtocupacion.getText().isEmpty() ||
        txtTalla.getText().isEmpty() || cbpeso.getSelectedIndex() == -1) {
        return false;
    }
    return true;
}
    private void cargarTabla(){
        
        DefaultTableModel modelotabla = (DefaultTableModel) detallespaciente.getModel();

        modelotabla.setRowCount(0);
        
        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        
        int columnas;
        
        
        try {
         
            Connection con = cone.obtenerconexion();
            ps = con.prepareStatement("SELECT Id_paciente, Nombre, Apellido, Telefono, Edad, Etapa_vida, Sexo, Correo, Peso, "
                    + "Talla, Tipo_paciente, Fecha_Nacimiento, Estado_Civil, Nacionalidad, Ocupacion, Direccion\n" +
                    "FROM Paciente;");
            rs = ps.executeQuery();
            //Extrae las columnas que hay en la BDD y las manda a la variable columna para iterar respecto a ese tamano
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            
            while (rs.next()) {
                Object[] fila = new Object[columnas];
                for (int i = 0; i < columnas; i++) {
                    //Extrae la informacion de la base de datos
                    fila[i] = rs.getObject(i + 1);
                }
                modelotabla.addRow(fila);
            }
            
            
            
        } catch (SQLException e) {
            
            JOptionPane.showMessageDialog(null, e);
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(paciente.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(paciente.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(paciente.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(paciente.class.getName()).log(Level.SEVERE, null, ex);
                }
                new paciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateChooser;
    private javax.swing.ButtonGroup RadioButtonSexo;
    private javax.swing.JButton btnabrircarpeta;
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btnbuscarcarpeta;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnmenu;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JComboBox<String> cbEtapaVida;
    private javax.swing.JComboBox<String> cbedad;
    private javax.swing.JComboBox<String> cbestadocivil;
    private javax.swing.JComboBox<String> cbpeso;
    private javax.swing.JComboBox<String> cbtipopaciente;
    private javax.swing.JTable detallespaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbfemenino;
    private javax.swing.JRadioButton rbmasculino;
    private javax.swing.JTextField txtTalla;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtidentidad;
    private javax.swing.JTextField txtnacionalidad;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtocupacion;
    private javax.swing.JTextField txtruta;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
